//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duv.Blogging.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Entries = new HashSet<Entry>();
            this.Blogs = new HashSet<Blog>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Entry> Entries { get; set; }
        public virtual ICollection<Blog> Blogs { get; set; }
    }
}
