//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Duv.Blogging.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post : Entry
    {
        public Post()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public string PermaLink { get; set; }
    
        public virtual Blog Blog { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
